name: Settings Sync incident
description: Incident impacting Visual Studio Code Settings Sync
title: "[Settings Sync]: "
labels: ["settings sync"]
body:
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Insiders
        - Stable
    validations:
      required: true
  - type: dropdown
    id: regions
    attributes:
      label: Impacted Region(s)
      multiple: true
      options:
        - Asia South-East
        - Europe West
        - US East
        - US West2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A brief description of the customer impact.
    validations:
      required: true
